
module.exports = {
  iOSsidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'iOS', // Generate sidebar slice from docs/tutorials/hard
    },
  ],
  androidSidebar: [
    'intro_android',
    {
      type: 'autogenerated',
      dirName: 'Android', // Generate sidebar slice from docs/tutorials/hard
    } 
  ],
  generalSidebar: [
    'intro_general',
    {
      type: 'autogenerated',
      dirName: 'General', // Generate sidebar slice from docs/tutorials/hard
    }
  ],
  englishSidebar: [
    'intro_english',
    {
      type: 'autogenerated',
      dirName: 'English', // Generate sidebar slice from docs/tutorials/hard
    }
  ]
};
